services:
  app:
    build: ./backend
    ports:
      - 8000:8000
      - 5173:5173
    volumes:
      - ./backend:/app
      - /app/vendor
      - /app/node_modules
    depends_on:
      - db
  db:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=dcs
  adminer:
    image: adminer
    ports:
      - 8080:8080
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
    depends_on:
      - app
    
